### PR TITLE
Update the CI config to switch to jdk 8

### PR DESCRIPTION
**Pull request by kangzhang**
Looks like jdk7 is no longer supported, let's switch to jdk8. travis-ci/travis-ci#7884

### CODE REVIEW

**Comment by ttung** [comment]
Kang

**Comment by ttung** [comment]
Also, I think you're pretty much on your own here.  YOLO MERGE.

**Comment by kangzhang** [comment]
Yeah, let's wait for the CI result. lol

**Comment by ttung** [comment]
WTF.  Kang makes no mistakes.

**Pull request merged**
