### PR TITLE
Support upcoming "source abi" feature of Buck

### PR DESCRIPTION
**Pull request by dreiss**

### CODE REVIEW

**Comment by ttung** [comment]
I think @Tylerk or @Kang need to approve this.

**Comment by kangzhang** [comment]
The changes look good! I'll try merging this later. 

Could we add some tests for it?

**Comment by dreiss** [comment]
Sure.  I'll need to run the AP with that special parameter added.  Do you know where would be the best place to integrate it?

**Comment by kangzhang** [comment]
Ah, I think it could be added in compiler args. e.g. https://github.com/Instagram/ig-json-parser/blob/master/processor/testuut/noserializers/build.gradle#L7

**Comment by kangzhang** [comment]
The ci config on master was broken due to changes on travis ci. I just updated the config and if you rebase the ci build should work again.

**Comment by dreiss** [comment]
Thanks for the pointer!  Updated the first commit with tests based on the noserializers tests.  The second one can't really be tested fully without the javac plugin in Buck.

**Comment by kangzhang** [comment]
Thanks for adding the test! Merging now.

**Pull request merged**
